apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: calculator-ro
  namespace: calculator-app
spec:
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: calculator-app
        image: 024848485298.dkr.ecr.us-west-2.amazonaws.com/microservicea:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          
  selector:
    matchLabels:
      app: calculator-app
  replicas: 10
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {}
